services:
  mail-exporter:
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: mail-export
    container_name: mail-export
    ports:
      - 8000:8000
    volumes:
      - ./:/home/app
      - /mnt/mailboxes:/home/data/
    depends_on:
      - mail-redis
      - mail-rabbit-mq

  mail-redis:
    image: redis
    container_name: mail-redis
    hostname: mail-redis
    volumes:
      - py-redis-data:/data
    ports:
      - 6379:6379
  migrate_celery:
    container_name: celery_worker
    build: .
    command: celery -A Celery worker -l info --without-gossip --without-mingle --without-heartbeat -Ofair --pool=solo
    volumes:
      - .:/app
    depends_on:
      - mail-redis

  mail-rabbit-mq:
    image: rabbitmq:latest
    container_name: mail-rabbitmq
    hostname: mail-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=mailexport
      - RABBITMQ_DEFAULT_PASS=m@ilexp0rt
    ports:
      - 5672:5672

volumes:
  py-redis-data:


